package com.revature.exceptions;

public class FirstException {
	public static void main(String[] args) {
		int x = 20;
		int y = 0;
		int result = 0; 
		
		try { // once an exception is caught in a try block, it will skip the rest of the code.
			System.out.println("Before Exception");
		result = x/y;
		System.out.println("After Exception .... ");
		} catch(ArithmeticException e) {
			System.out.println("Catching the exception.");
		}
		System.out.println("Result= " + result);
		System.out.println("Done . . . . . . . ");
	}

}
