package com.revature.exceptions;

public class FirstException {
	public static void main(String[] args) {
		int x = 20;
		int y = 0;
		int result = 0; 
		
		try {
		result = x/y;
		} catch(ArithmeticException e) {
			
		}
		System.out.println("Result= " + result);
		System.out.println("Done . . . . . . . ");
	}

}
